import { useState } from 'react'
import type { WizardData } from '../AdventureWizard'
import type { QuestLength } from '../../../types/quest'

interface Props {
  data: WizardData
  onNext: (patch: Pick<WizardData, 'questEnabled' | 'questLength' | 'questContextHint'>) => void
  onBack: () => void
  isSubmitting: boolean
}

const LENGTH_OPTIONS: { value: QuestLength; label: string; desc: string }[] = [
  { value: 'short', label: 'Short', desc: '3 steps — quick resolution' },
  { value: 'medium', label: 'Medium', desc: '5 steps — standard arc' },
  { value: 'long', label: 'Long', desc: '8+ steps — epic campaign' },
]

export default function QuestSetupStep({ data, onNext, onBack, isSubmitting }: Props) {
  const [enabled, setEnabled] = useState(data.questEnabled)
  const [length, setLength] = useState<QuestLength>(data.questLength)
  const [hint, setHint] = useState(data.questContextHint)

  return (
    <div className="flex flex-col gap-5">
      <p className="text-sm text-zinc-400">
        Optionally start with an opening quest generated by the DM. You can always create quests
        later from within the adventure.
      </p>

      <label className="flex items-center gap-3 cursor-pointer">
        <div
          onClick={() => setEnabled((v) => !v)}
          className={`w-10 h-5 rounded-full relative transition-colors duration-150 ${
            enabled ? 'bg-accent' : 'bg-zinc-700'
          }`}
        >
          <div
            className={`absolute top-0.5 w-4 h-4 bg-white rounded-full shadow transition-transform duration-150 ${
              enabled ? 'translate-x-5' : 'translate-x-0.5'
            }`}
          />
        </div>
        <span className="text-sm text-zinc-300">Generate an opening quest</span>
      </label>

      {enabled && (
        <>
          <div className="flex flex-col gap-1.5">
            <label className="text-xs uppercase tracking-wider text-zinc-400">Quest Length</label>
            <div className="flex gap-2">
              {LENGTH_OPTIONS.map((opt) => (
                <button
                  key={opt.value}
                  onClick={() => setLength(opt.value)}
                  className={`flex-1 p-2.5 rounded-xl border text-left transition-all duration-150 ${
                    length === opt.value
                      ? 'border-accent bg-accent/10 text-zinc-100'
                      : 'border-zinc-700 hover:border-zinc-600 text-zinc-400'
                  }`}
                >
                  <div className="text-sm font-semibold">{opt.label}</div>
                  <div className="text-xs text-zinc-500 mt-0.5">{opt.desc}</div>
                </button>
              ))}
            </div>
          </div>

          <div className="flex flex-col gap-1.5">
            <label className="text-xs uppercase tracking-wider text-zinc-400">
              Context Hint (optional)
            </label>
            <textarea
              value={hint}
              onChange={(e) => setHint(e.target.value)}
              placeholder="A missing shipment of weapons, a corrupt noble, a monster terrorizing the road..."
              rows={3}
              className="bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 px-3 py-2.5 rounded-xl text-sm focus:outline-none focus:border-accent transition-colors duration-150 resize-none"
            />
          </div>
        </>
      )}

      <div className="flex justify-between pt-2">
        <button
          onClick={onBack}
          className="px-4 py-2 text-sm text-zinc-400 hover:text-zinc-100 transition-colors duration-150"
        >
          Back
        </button>
        <button
          onClick={() => onNext({ questEnabled: enabled, questLength: length, questContextHint: hint })}
          disabled={isSubmitting}
          className="px-5 py-2 bg-accent hover:bg-accent-hover text-zinc-950 font-semibold rounded-xl transition-colors duration-150 disabled:opacity-60"
        >
          {isSubmitting ? 'Creating...' : 'Launch Adventure'}
        </button>
      </div>
    </div>
  )
}
